blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog_app.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('blog_app.urls', namespace='blog_app')), # namespaces have to be unique across your entire project. 
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

blog/blog_app/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = "blog_app"

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

blog/blog_app/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status = Post.Status.PUBLISHED)

class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = "DF", "Draft",
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250,
        unique_for_date='publish'
        )
    body = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='blog_posts'
    )
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT
    )
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish'] # to indicate descending order by using a hyphen before the field name

    indexes = [
        models.Index(fields=['-publish']),
    ]
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog_app:post_detail', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])
    
class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/blog_app/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form): # inherits from Form class
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Name'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'exampleFormControlInput1', 'placeholder': 'name@example.com'}))
    to = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'exampleFormControlInput1', 'placeholder': 'name@example.com'}))
    comments = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'exampleFormControlTextarea1', 'rows': '3'}))

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Your Email'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'placeholder': 'Your Comment'}),
        }

class SearchForm(forms.Form):
    query = forms.CharField()

blog/blog_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.db.models import Count # aggregation function of the Django ORM 
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import (
    SearchVector,
    SearchQuery,
    SearchRank
)
from django.contrib.postgres.search import TrigramSimilarity
from django.views.decorators.http import require_POST
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag

def post_list(request, tag_slug = None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        # if page_number is out of range get last page of results
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        # if page_number is not an integer get the first page
        posts = paginator.page(1)
    return render(request, 'blog_app/post/list.html', {'posts': posts, 'tag': tag})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
        status=Post.Status.PUBLISHED,
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')
    ).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog_app/post/detail.html', {'post': post, 'comments': comments, 'form': form, 'similar_posts': similar_posts})

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['email'])
            # send email
            send_mail(subject, message, None, [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog_app/post/share.html', {'post': post, 'form': form, 'sent': sent})

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    return render(
        request,
        'blog_app/post/comment.html',
        {
            'post': post,
            'form': form,
            'comment': comment
        }
    )

def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = (
                Post.published.annotate(
                    similarity=TrigramSimilarity('title', query),
                )
                .filter(similarity__gt=0.1)
                .order_by('-similarity')
            )
    return render(
        request,
        'blog_app/post/search.html',
        {
            'form': form,
            'query': query,
            'results': results
        }
    )

#def post_detail(request, id):
#    try:
#        post = Post.published.get(id=id)
#    except Post.DoesNotExist:
#        raise Http404("Post does not exist")
#    return render(request, 'blog_app/post/detail.html', {'post': post})

blog/blog_app/templates/blog_app/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class = "row">
        <div class="col-md-2">
            <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary" style="width: 280px">
              <a href="{% url "blog_app:post_list" %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                <span class="fs-4">Blog App</span>
              </a>
              <hr>
              <p>I've written {% total_posts %} posts so far.</p>
              <p>
                <a href="{% url "blog_app:post_feed" %}">
                  Subscribe to my RSS feed
                </a>
              </p>
              <a href="{% url "blog_app:post_search" %}">
                <button type="button" class="btn btn-secondary">Search</button>
              </a>
              <hr>
              <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                  <h5>Latest posts</h5>
                  {% show_latest_posts 3 %}
                </li>
                <hr>
                <li>
                  <h5>Most commented posts</h5>
                  {% get_most_commented_posts as most_commented_posts %}
                  <ul>
                    {% for post in most_commented_posts %}
                      <li>
                        <i class="bi bi-chat-square-dots"></i> <!-- Eğer bir ikon kullanmak isterseniz, bu örnekte Bootstrap Icons'tan birini kullandım -->
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                      </li>
                    {% endfor %}
                  </ul>
                </li>
              </ul>
            </div>
          </div>          
    <div class="container col-md-9">
        <br>
        {% block content %}
        {% endblock %}
    </div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

blog/blog_app/templates/blog_app/pagination.html
<div class="pagination">
    <span class="step-links">
      {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="rgb(50, 168, 82)" class="bi bi-arrow-left-square" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm11.5 5.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"/>
          </svg>
        </a>
      {% endif %}
      <div  style="display: inline-block;">
        <span class="current">
          Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
      </div>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="rgb(50, 168, 82)" class="bi bi-arrow-right-square" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm4.5 5.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z"/>
          </svg>
        </a>
      {% endif %}
    </span>
  </div>

blog/blog_app/templates/blog_app/post/comment.html
{% extends "blog_app/base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
  {% if comment %}
    <h2>Your comment has been added.</h2>
    <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
  {% else %}
    {% include "blog_app/post/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

blog/blog_app/templates/blog_app/post/detail.html
{% extends "blog_app/base.html" %}
{% load blog_tags %}
{% load static %}
{% block title %}{{post.title}}{% endblock title %}
{% block content %}
  <div style="display: flex;">
    <div style="flex: 1;"><h1>{{ post.title }}</h1></div>
    <div style="">
      <p>
        <a href="{% url "blog_app:post_share" post.id %}">
          <button type="button" class="btn btn-success">Share via email</button>
        </a>
      </p>
    </div>
  </div>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|markdown }}
  <br>
  <br>
  <div class="row">
    <div class="col-md-6">
      {% with comments.count as total_comments %}
        <h2>
          {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
      {% endwith %}
      {% for comment in comments %}
        <div class="comment">
          <p class="info text-body-secondary">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
          </p>
          {{ comment.body|linebreaks }}
        </div>
      {% empty %}
        <p>There are no comments.</p>
      {% endfor %}
    </div>
    <div class="col-md-6" style="border-left: 1px solid #ccc; padding-left: 15px;">
      {% include "blog_app/post/include/comment_form.html" %}
    </div>
  </div>
  <br>
  <h2>Similar posts</h2>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for post in similar_posts %}
      <div class="col">
        <div class="card h-100">
          <img src="{% static "/images/blog.png" %}" class="img- rounded-start" style="max-height: 200px; max-width: 200px;" alt="{{ post.title }}">
          <div class="card-body">
            <h5 class="card-title"><a href="{{ post.get_absolute_url }}" style="text-decoration: none">{{ post.title }}</a></h5>
            <p class="card-text">{{ post.body }}</p>
          </div>
          <div class="card-footer">
            <small class="text-body-secondary">Last updated {{ post.updated }} ago</small>
          </div>
        </div>
        <br>
      </div>
    {% empty %}
      <p>There are no similar posts yet.</p>
    {% endfor %}
  </div>
{% endblock %}

blog/blog_app/templates/blog_app/post/include/comment_form.html
<div style="max-width: ">
  <h2>Add a new comment</h2>
  <form action="{% url "blog_app:post_comment" post.id %}" method="post">
      <div class="left">
      {{ form.name.as_field_group }}
      </div>
      <div class="left">
      {{ form.email.as_field_group }}
      </div>
      {{ form.body.as_field_group }}
    {% csrf_token %}
    <br>
    <p style="text-align: right;"><input type="submit" class="btn btn-primary" value="Add comment"></p>
  </form>
</div>

blog/blog_app/templates/blog_app/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
    {% endfor %}
  </ul>

blog/blog_app/templates/blog_app/post/list.html
{% extends "blog_app/base.html" %}
{% load blog_tags %}
{% load static %}
{% block title %}Blog Site{% endblock title %}
{% block content %}
{% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
{% for post in posts %}
<div class = "">
    <div class="card mb-3" style="min-height: 180px;">
        <div class="row g-0">
            <div class="col-md-2 text-center">
                <img src="{% static "/images/blog.png" %}" class="img-fluid rounded-start" style="max-height: 180px;" alt="{{ post.title }}">
            </div>
            <div class="col-md-10">
                <div class="card-body" style="display: flex; flex-direction: column; justify-content: center; height: 100%;">
                    <h5 class="card-title"><a href="{{ post.get_absolute_url }}" style="text-decoration: none">{{ post.title }}</a></h5>
                    <p class="card-text">{{ post.body|markdown|truncatewords_html:30 }}</p>
                    <p class="tags">
                        Tags:
                        {% for tag in post.tags.all %}
                          <a href="{% url "blog_app:post_list_by_tag" tag.slug %}">
                            {{ tag.name }}
                          </a>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                     </p>
                    <p class="card-text"><small class="text-body-secondary">Published on {{ post.publish }}</small></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div class = "d-flex justify-content-center">
    {% include "blog_app/pagination.html" with page=posts %}
</div>
{% endblock content %}

blog/blog_app/templates/blog_app/post/search.html
{% extends "blog_app/base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4>
        <a href="{{ post.get_absolute_url }}">
          {{ post.title }}
        </a>
      </h4>
      {{ post.body|markdown|truncatewords_html:12 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog_app:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

blog/blog_app/templates/blog_app/post/share.html
{% extends "blog_app/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
<div style="max-width: 560px;">
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <p style="text-align: center;"><input type="submit" class="btn btn-primary" value="Send Mail"></p>
    </form>
  {% endif %}
</div>
{% endblock %}